server.port=${PORT:8080}
spring.application.name=underwriting-service
spring.http.converters.preferred-json-mapper=jackson2
spring.jackson.use-jackson2-defaults=true
management.endpoints.web.exposure.include=health,info
eureka.client.serviceUrl.defaultZone=${EUREKA_URL:http://eureka-server.apps.internal:8080/eureka}
eureka.instance.hostname=${EUREKA_INSTANCE_HOSTNAME:${spring.application.name}.apps.internal}
eureka.instance.prefer-ip-address=false
logging.pattern.dateformat=yyyy-MM-dd HH:mm:ss.SSS
# TODO [Advisor]: Liveness and readiness probes are now enabled by default in Spring Boot 4.0. If you do not need those probes, keep this property. Otherwise, delete this property to adopt the new defaults. See https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-4.0-Migration-Guide#liveness-and-readiness-probes
management.endpoint.health.probes.enabled=false
# [Spring Advisor]: This property disables health-group-membership-validation with boot 3.1 for backwards compatible reasons, but the Spring team encourages to enable it.
management.endpoint.health.validate-group-membership=false
# TODO: [Advisor] Strongly recommended to configure the `management.endpoints.jmx.exposure.include` to expose ONLY required information
management.endpoints.jmx.exposure.include=*
eureka.instance.non-secure-port=${server.port}
demo.timezone=America/Chicago
